### ISSUE TITLE
Support all feed item types

### ISSUE THREAD

**Issue by dblock** [dblock/slack-arena#5]
I copied [some code](https://github.com/dblock/slack-arena/blob/master/slack-arena/models/channel.rb#L43) from https://github.com/garrying/arena-slack for feed item types, but what's actually supported in channel feed (eg. https://api.are.na/v2/channel/photographing-people-in-the-streets-of-havana-cuba/feed?per=2&page=2)?

The format is "[user] [action] [item] [connector] [target]" (e.g. DB added image to Photographing People in the Streets of Havana, Cuba). There is also a [parent] attribute there that is commonly used to hold the connection data (i.e. the specific relationship of the block to the channel).

/cc: @dzucconi if you could help clarify? add to https://github.com/aredotna/arena-rb/pull/2?

**Comment by dzucconi** [comment]
Well what I do know is: there are no real types. There are just strings for `action`, and `to` and combinations of various block types. It's a grab bag with no enforcement of anything and I'm not really sure what could be considered "valid."

The following `action`s at least exist, though I suspect we aren't minting some of these anymore.

`["created", "replied to", "published", "followed", "has joined Arena", "said", "mentioned you", "added", "commented on", "is collaborating with"]`

and the following `to` fields: `[nil, "on", "to"]`

@broskoski, can you enumerate a list of "valid" combinations that are actually seen in the wild?

**Comment by broskoski** [comment]
The `action`s seen in the wild: 

`["created", "followed", "mentioned you", "added", "commented on", "is collaborating with"]`

For channels, the only real relevant `action` (in the context of a slack bot) is `added`.

**Comment by dzucconi** [comment]
However @broskoski there also exist totally invalid possibilities of combinations here.

What are all the possible combinations of action, to, parent, target (I think those are the only relevant ones?)?

**Comment by broskoski** [comment]
`[user]``[action]``[item]``[connector]``[target]`



### Actions
- `created` - Refers to channel creation. `item` will always be a Channel.
- `followed` - Refers to a user following either a channel or another user. `item` can either be a User or a Channel.
- `added` -  Refers to a connection to a channel. `item` can either be a Channel or a Block. `connector` will always be "to". `target` will always be a Channel. This feed item will also have a `parent` attribute that will contain the `connection` record. 
- `commented on` - Refers to a comment on a block. `item` will be a Comment. `target` will always be a Block.
- `is collaborating with` - Refers to a User being added to collaborate on a Channel. `item` will always be a User. `target` will always be a channel.

**Comment by dzucconi** [comment]
Alright, so I just generated a list of actual possibilities

```
action:followed * item_type:User
action:followed * item_type:Channel

action:added * item_type:Block * connector:to * target_type:Channel * parent_type:Connection
action:added * item_type:Channel * connector:to * target_type:Channel * parent_type:Connection

action:created * item_type:Channel

action:is collaborating with * item_type:User * connector:on * target_type:Channel * parent_type:Membership

action:commented on * item_type:Comment * target_type:Block * parent_type:Channel

action:mentioned you * item_type:Comment * target_type:User * parent_type:Block
```

**Comment by dblock** [comment]
I did a lot of the work in https://github.com/dblock/slack-arena/commit/4bf043209cbb40191cc0f7a52a61141f802c7eae, and have some sample feed items extracted [here](https://github.com/dblock/slack-arena/tree/master/spec/fixtures/arena/test-channel).
